version: '3'
services:
  database:
    platform: linux/amd64
    container_name: appdb
    image: mysql:5.7.41
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_docker
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  phpapache:
    build: ./phpapache
    container_name: "phpapache"
    volumes:
      - ./php-app/html:/var/www/html
      - ./phpapache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./phpapache/symfonyinstall.sh:/var/www/symfonyinstall.sh
    ports:
      - 80:80
    depends_on:
      - database